### ISSUE TITLE
Patching datasets using Java client does not work.

### ISSUE THREAD

**Issue by JeremyMcCormick** [slaclab/datacat#9]
Patching an existing dataset using the Java API does not work correctly or at least not how I would expect.

I get this error message:

Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'CheckSum' at row 1

I'm calling the patch method as follows ...

client.patchDataset(folder + "/" + dataset.getName(), "current", site, dataset);

The dataset being patched has all version metadata set on the object including checksum, eventCount, etc. just as if it were a new dataset.

My intention is that the existing version metadata can be ignored, but instead it seems that maybe the code does not like it that checksum is already set on the object (not sure -- just a guess).

**Comment by brianv0** [comment]
Okay, so I think I changed checksum it to a string type a while back, but the API assumes that string is hex (base-16) and converts it to/from a number when going in/out of the database.

https://github.com/slaclab/datacat/blob/master/datacat-impl/src/main/java/org/srs/datacat/dao/sql/mysql/DatasetDAOMySQL.java#L765

But, silently it ignores the checksum when creating datasets:
https://github.com/slaclab/datacat/blob/master/datacat-impl/src/main/java/org/srs/datacat/dao/sql/mysql/DatasetDAOMySQL.java#L522

The second part, ignoring when creating a dataset, is definitely a bug. The first case *should* work. I'm pretty sure it if I do something like `intValue()` at the end of line 766, but it should just work in any case.

**Comment by JeremyMcCormick** [comment]
Thanks for looking at this.

Is there any workaround I can do for the time being so that it just skips looking at the checksum entirely when patching?  Or should I just wait for a fix?

**Comment by brianv0** [comment]
You could checkout checksum_fix, build it, and try that out.
